package com.example.clientforspringsecuritypetshop.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.clientforspringsecuritypetshop.model.Pet;

import com.example.clientforspringsecuritypetshop.model.PetDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig petDaoConfig;

    private final PetDao petDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        petDaoConfig = daoConfigMap.get(PetDao.class).clone();
        petDaoConfig.initIdentityScope(type);

        petDao = new PetDao(petDaoConfig, this);

        registerDao(Pet.class, petDao);
    }
    
    public void clear() {
        petDaoConfig.clearIdentityScope();
    }

    public PetDao getPetDao() {
        return petDao;
    }

}
